/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMentoriaRouteImport } from './routes/_authenticated/mentoria'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedCadastroEventosRouteImport } from './routes/_authenticated/cadastro-eventos'
import { Route as AuthenticatedCadastroRouteImport } from './routes/_authenticated/cadastro'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMentoriaRoute = AuthenticatedMentoriaRouteImport.update({
  id: '/mentoria',
  path: '/mentoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagnosticoRoute =
  AuthenticatedDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroEventosRoute =
  AuthenticatedCadastroEventosRouteImport.update({
    id: '/cadastro-eventos',
    path: '/cadastro-eventos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroRoute = AuthenticatedCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/cadastro': typeof AuthenticatedCadastroRoute
  '/cadastro-eventos': typeof AuthenticatedCadastroEventosRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/mentoria': typeof AuthenticatedMentoriaRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/cadastro': typeof AuthenticatedCadastroRoute
  '/cadastro-eventos': typeof AuthenticatedCadastroEventosRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/mentoria': typeof AuthenticatedMentoriaRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/cadastro': typeof AuthenticatedCadastroRoute
  '/_authenticated/cadastro-eventos': typeof AuthenticatedCadastroEventosRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/_authenticated/mentoria': typeof AuthenticatedMentoriaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cadastro'
    | '/cadastro-eventos'
    | '/diagnostico'
    | '/mentoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/cadastro'
    | '/cadastro-eventos'
    | '/diagnostico'
    | '/mentoria'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/cadastro'
    | '/_authenticated/cadastro-eventos'
    | '/_authenticated/diagnostico'
    | '/_authenticated/mentoria'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mentoria': {
      id: '/_authenticated/mentoria'
      path: '/mentoria'
      fullPath: '/mentoria'
      preLoaderRoute: typeof AuthenticatedMentoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnostico': {
      id: '/_authenticated/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AuthenticatedDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro-eventos': {
      id: '/_authenticated/cadastro-eventos'
      path: '/cadastro-eventos'
      fullPath: '/cadastro-eventos'
      preLoaderRoute: typeof AuthenticatedCadastroEventosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro': {
      id: '/_authenticated/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthenticatedCadastroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCadastroRoute: typeof AuthenticatedCadastroRoute
  AuthenticatedCadastroEventosRoute: typeof AuthenticatedCadastroEventosRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRoute
  AuthenticatedMentoriaRoute: typeof AuthenticatedMentoriaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCadastroRoute: AuthenticatedCadastroRoute,
  AuthenticatedCadastroEventosRoute: AuthenticatedCadastroEventosRoute,
  AuthenticatedDiagnosticoRoute: AuthenticatedDiagnosticoRoute,
  AuthenticatedMentoriaRoute: AuthenticatedMentoriaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
