ALTER TABLE public.clientes 
  ADD COLUMN IF NOT EXISTS imersao TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS senha TEXT NOT NULL DEFAULT '';